name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "e2e-web-demo" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'BrowserStack Env Setup'
        uses: browserstack/github-actions/setup-env@master
