name: CI
on:
  pull_request:
    branches: [main]  # Only run for PRs targeting main
jobs:
  build:
    name: CI / build (pull_request)  # Must match required check name
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: 'Running A11y test on Automate'
        run: |
          export BROWSERSTACK_CONFIG_FILE=src/test/resources/conf/capabilities/browserstack.yml
          mvn clean test -P bstack-parallel-browsers

      - name: 'Check for Assertion Failures'
        if: always()
        run: |
          echo "Checking for assertion failures..."
          
          if grep -q "AssertionError" target/surefire-reports/*.txt; then
            echo "❌ Assertion failures detected in the test logs."
            
            exit 1
          else
            echo "✅ No assertion failures found."
          fi
          
