name: CI

on:
  push:
    branches: [ "main" ]  #
  pull_request:
    branches: [ "SiddhiRao10-MainA11y" ]  # 
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: 'BrowserStack Env Setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: 'dd'
          access-key: 'ddd'

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: 'Running A11y test on Automate'
        run: |
          export BROWSERSTACK_CONFIG_FILE=src/test/resources/conf/capabilities/browserstack.yml
          mvn clean test -P bstack-parallel-browsers
